### PR TITLE
Bundle library

### PR DESCRIPTION
**Pull request by beeglebug**
Hi, I was interested in using this library, but noticed an open issue to get it bundled and published, so thought i'd have a quick stab at a basic rollup config.

In this initial version i've only exported the files necessary to replicate the code in `runner.js` (`GraphEvaluator`, `loadGraph`, `NodeRegistry` and `registerGenericNodes`). 

I assume there is other code which would be helpful to a user of the library, but until I can play around with it a bit more, I thought it best to raise it now and ask what else to add.

### CODE REVIEW

**Comment by beeglebug** [comment]
ok so exec is all fixed now, i've changed `Runner.ts` to `Runner.js` and set node up in esm mode via `type: module` in package.json and its all good. Only thing I need a bit of input on is what else to export in `index.ts` I guess?

**Comment by bhouston** [comment]
This is amazing!  I'll have a look now!

**Comment by bhouston** [comment]
Thank you!  I just added a bunch more exports and it worked great!

**Comment by bhouston** [comment]
It is now also available on npm: https://www.npmjs.com/package/behave-graph

There was already a "behavior-graph" on npm so I changed the name to "behave-graph" for now.

**Pull request merged**
